# Generated by Django 3.2.8 on 2022-01-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(default='', max_length=128, verbose_name='nazwa_uslugi')),
                ('service_number', models.CharField(default='', max_length=256, verbose_name='numer_uslugi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='cena')),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='opis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pricing/', verbose_name='zdjecie')),
            ],
            options={
                'ordering': ['service_name'],
            },
        ),
    ]
