# Generated by Django 3.2.8 on 2022-01-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='vehicle',
            field=models.CharField(default='', max_length=128, verbose_name='rodzaj pojazdu'),
        ),
    ]
