# Generated by Django 3.2.8 on 2022-01-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_pricing_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricing',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='cena'),
        ),
    ]
