# Generated by Django 3.2.8 on 2022-01-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0003_alter_pricing_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricing',
            options={'ordering': ['service_number']},
        ),
        migrations.AlterField(
            model_name='pricing',
            name='service_number',
            field=models.DecimalField(decimal_places=0, max_digits=20, verbose_name='numer_uslugi'),
        ),
    ]
