# Generated by Django 3.2.8 on 2022-01-11 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Nazwa')),
                ('description', models.TextField(blank=True, default='', max_length=1024, null=True, verbose_name='Opis')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('h', 'zatrudniony'), ('d', 'zwolniony'), ('t', 'wypowiedzenie')], default='h', max_length=1),
        ),
        migrations.AddField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.position', verbose_name='Stanowisko'),
        ),
    ]
