# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWarsztatzamowienie():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_warsztatzamowienie(self):
    self.driver.get("http://127.0.0.1:8000/home/")
    self.driver.set_window_size(1384, 780)
    self.driver.find_element(By.CSS_SELECTOR, ".tile1:nth-child(1) .icon-user").click()
    self.driver.find_element(By.ID, "id_username").send_keys("test")
    self.driver.find_element(By.ID, "id_password").click()
    self.driver.find_element(By.ID, "id_password").send_keys("ifdOxoycVX5T7mG")
    self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
    self.driver.find_element(By.LINK_TEXT, "Nasza oferta").click()
    self.driver.find_element(By.LINK_TEXT, "Personalizuj Zamówienie").click()
    self.driver.find_element(By.ID, "id2").click()
    dropdown = self.driver.find_element(By.ID, "id2")
    dropdown.find_element(By.XPATH, "//option[. = 'Samochód Osobowy']").click()
    self.driver.find_element(By.ID, "id1").click()
    dropdown = self.driver.find_element(By.ID, "id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Silnik']").click()
    self.driver.find_element(By.ID, "silnik1").click()
    self.driver.find_element(By.ID, "zdjengine").click()
    self.driver.find_element(By.ID, "zdjengine").click()
    self.driver.find_element(By.ID, "silnik3").click()
    self.driver.find_element(By.ID, "btn").click()
    self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(2)").click()
    self.driver.find_element(By.ID, "payment_method").click()
    dropdown = self.driver.find_element(By.ID, "payment_method")
    dropdown.find_element(By.XPATH, "//option[. = 'BLIK']").click()
    self.driver.find_element(By.ID, "blik_code").click()
    self.driver.find_element(By.ID, "blik_code").send_keys("352176")
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn").click()
  
