# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWarsztat2():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_warsztat2(self):
    self.driver.get("http://127.0.0.1:8000/pricing/personalize/")
    self.driver.set_window_size(1384, 780)
    self.driver.find_element(By.ID, "id2").click()
    dropdown = self.driver.find_element(By.ID, "id2")
    dropdown.find_element(By.XPATH, "//option[. = 'Samochód Osobowy']").click()
    self.driver.find_element(By.ID, "id1").click()
    dropdown = self.driver.find_element(By.ID, "id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Silnik']").click()
    elements = self.driver.find_elements(By.ID, "zdjengine")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "id2").click()
    dropdown = self.driver.find_element(By.ID, "id2")
    dropdown.find_element(By.XPATH, "//option[. = 'Samochód Osobowy']").click()
    self.driver.find_element(By.ID, "id1").click()
    dropdown = self.driver.find_element(By.ID, "id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Przód']").click()
    elements = self.driver.find_elements(By.ID, "zdjfront")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "id2").click()
    dropdown = self.driver.find_element(By.ID, "id2")
    dropdown.find_element(By.XPATH, "//option[. = 'Chopper']").click()
    self.driver.find_element(By.ID, "id1").click()
    dropdown = self.driver.find_element(By.ID, "id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Silnik']").click()
    elements = self.driver.find_elements(By.ID, "zdjengine")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "id2").click()
    dropdown = self.driver.find_element(By.ID, "id2")
    dropdown.find_element(By.XPATH, "//option[. = 'Motocykl']").click()
    self.driver.find_element(By.ID, "id1").click()
    dropdown = self.driver.find_element(By.ID, "id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Wewnątrz']").click()
    elements = self.driver.find_elements(By.ID, "zdjinside")
    assert len(elements) > 0
  
