# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestWarsztatzamowienieraz():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_warsztatzamowienieraz(self):
    self.driver.get("http://127.0.0.1:8000/pricing/personalize/")
    self.driver.set_window_size(1384, 780)
    self.driver.find_element(By.ID, "id2").click()
    dropdown = self.driver.find_element(By.ID, "id2")
    dropdown.find_element(By.XPATH, "//option[. = 'Samochód Osobowy']").click()
    self.driver.find_element(By.ID, "id1").click()
    dropdown = self.driver.find_element(By.ID, "id1")
    dropdown.find_element(By.XPATH, "//option[. = 'Silnik']").click()
    self.driver.find_element(By.ID, "silnik1").click()
    WebDriverWait(self.driver, 0.001).until(expected_conditions.invisibility_of_element_located((By.ID, "silnik1")))
    self.driver.find_element(By.ID, "silnik2").click()
    WebDriverWait(self.driver, 0.001).until(expected_conditions.invisibility_of_element_located((By.ID, "silnik2")))
    self.driver.find_element(By.ID, "silnik3").click()
    WebDriverWait(self.driver, 0.001).until(expected_conditions.invisibility_of_element_located((By.ID, "silnik3")))
  
